version: "3.9"

services:
  db:
    image: postgres:15
    container_name: finance_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: finance_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3

  frontend:
    build: ./frontend
    container_name: finance_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - finance-net

volumes:
  pgdata:

networks:
  finance-net:
